name: Release to modrinth

on:
  push:
    tags: [ 'v*' ]

env:
  VERSION: ${{ github.ref }}

jobs:
  # Run a build first
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Ensure gradlew is executable
        run: chmod +x gradlew
      - name: Validate the gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with gradle
        run: ./gradlew build --stacktrace

  # Publish a new release on GitHub
  github-release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Ensure gradlew is executable
        run: chmod +x gradlew
      - name: Validate the gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with gradle
        run: ./gradlew build --stacktrace
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  # Publish a new version to Modrinth
  modrinth-publish:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Ensure gradlew is executable
        run: chmod +x gradlew
      - name: Validate the gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish to Modrinth
        run: ./gradlew publishModrinth --stacktrace
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
